### ISSUE TITLE
Relationship to other package repositories in this org?

### ISSUE THREAD

**Issue by bollwyvl** [errata-ai/packages#18]
What is the relationship between this repository, and the other like-named repositories to those found in `pkg`?

- https://github.com/errata-ai/alex
- https://github.com/errata-ai/Google
- https://github.com/errata-ai/hugo
- https://github.com/errata-ai/joblint
- https://github.com/errata-ai/Microsoft
- https://github.com/errata-ai/proselint
- https://github.com/errata-ai/readability
- https://github.com/errata-ai/write-good

Should this repo, or the specific other ones, be considered "canonical"? 

It looks like they all accept PRs and cut releases (with seemingly unrelated version lines), so it's a bit hard to tell.

**Comment by jdkato** [comment]
You can ignore the ones in `pkg`; the `library.json` file lists the "canonical" sources.
