### ISSUE TITLE
Actionables

### ISSUE THREAD

**Issue by brandonkal** [errata-ai/packages#2]
Actionables for #1 :

- [ ] Update docs to make it clear that a clone into StylesPath is supported (all the readme's suggest manual copying
- [ ] Add this project which is more a comprehensive collection of styles: [vale-styles](https://github.com/testthedocs/vale-styles/issues)

**Comment by jdkato** [comment]
1. I think the existing instructions list the required steps adequately: download a release, copy the style into your `StylesPath`, and include it in your config. There are many ways to go about implementing those steps and I don't think there's any reason to assume that typical Git operations wouldn't work as usual.
2. Those styles originally served as test cases in the actual Vale repo (I personally created every non-TTD style over there). As the test suite grew, I moved away from using those styles and TestTheDocs asked if they could maintain them. As is, though, they aren't more "comprehensive": most styles only include a few rules (e.g., the [`Rust`](https://github.com/testthedocs/vale-styles/tree/master/Rust) style only contains two) and the styles themselves don't contain any tests. So, they don't meet the criteria for inclusion here (eventually, I'll probably expand upon some of them, though, as I did with `Google`).
