### ISSUE TITLE
Chicago Style Guide?

### ISSUE THREAD

**Issue by kirkilj** [errata-ai/packages#7]
Is there any plan to include the Chicago Style Guide?

**Comment by jdkato** [comment]
Probably not.

The concept isn't really compatible with commercial style guides.

**Comment by kirkilj** [comment]
Since I'm relaying this question from some of our Tech Writers, can you clarify for me please? Are you referring to licensing issues or the ability for a regex-based solution to implement the Chicago Style Guide?

Cheers,

John

**Comment by jdkato** [comment]
> Are you referring to licensing issues or the ability for a regex-based solution to implement the Chicago Style Guide?

The former.

(In theory, at least, there's no technical reason why we *couldn't* support it.)
